-- Generated by SQL Maestro for MySQL. Release date 21/06/2011
-- 19/06/2015 11:13:35
-- ----------------------------------
-- Alias: api at localhost
-- Database name: api
-- Host: localhost
-- Port number: 3306
-- User name: root
-- Server: 5.6.12-log
-- Session ID: 5
-- Character set: latin1
-- Collation: latin1_swedish_ci
-- update 230-05-2018

CREATE DATABASE api
  CHARACTER SET latin1
  COLLATE latin1_swedish_ci;

USE api;

/* Tables */
CREATE TABLE clientes (
  id        int AUTO_INCREMENT NOT NULL,
  nome      varchar(20),
  telefone  varchar(20),
  PRIMARY KEY (id)
) ENGINE = MyISAM;

/* Data for table "clientes" */
INSERT INTO clientes (id, nome, telefone) VALUES
  (2, NULL, NULL),
  (3, NULL, NULL),
  (4, NULL, NULL),
  (5, NULL, NULL),
  (6, NULL, NULL),
  (7, 'galvao', '155'),
  (11, 'Superman', 'Stark'),
  (9, 'Arya Stark', 'merreu'),
  (10, NULL, NULL),
  (12, 'Jhon Snow', 'Sabe de nada!');
